In [1]:
import sys
import numpy as np

# Basic Numpy Arrays

In [2]:
np.array([1, 2, 3, 4])

array([1, 2, 3, 4])

In [3]:
a = np.array([1, 2, 3, 4])

In [4]:
b = np.array([0, .5, 1, 1.5, 2])

In [5]:
a

array([1, 2, 3, 4])

In [6]:
b

array([0. , 0.5, 1. , 1.5, 2. ])

In [7]:
a[0], a[1]

(1, 2)

In [8]:
a[0:]

array([1, 2, 3, 4])

In [9]:
a[1:3]

array([2, 3])

In [10]:
a[1:-1]

array([2, 3])

In [11]:
a[::2]

array([1, 3])

In [13]:
b

array([0. , 0.5, 1. , 1.5, 2. ])

In [14]:
b[0], b[2], b[-1]

(0.0, 1.0, 2.0)

In [15]:
b[[0, 2, -1]]

array([0., 1., 2.])

# Array Type

In [17]:
a

array([1, 2, 3, 4])

In [19]:
a.dtype

dtype('int64')

In [20]:
b

array([0. , 0.5, 1. , 1.5, 2. ])

In [21]:
b.dtype

dtype('float64')

In [23]:
np.array([1, 2, 3, 4], dtype = np.float)

/var/folders/gr/9w8v_1fn48ddjgbpp0c4s5cr0000gn/T/ipykernel_11397/3598171318.py:1: DeprecationWarning: `np.float` is a deprecated alias for the builtin `float`. To silence this warning, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  np.array([1, 2, 3, 4], dtype = np.float)


array([1., 2., 3., 4.])

In [24]:
np.array([1, 2, 3, 4], dtype = np.int8)

array([1, 2, 3, 4], dtype=int8)

In [25]:
c = np.array(['a', 'b', 'c'])

In [30]:
c.dtype

dtype('<U1')

In [27]:
d = np.array([{'a': 1}, sys])

In [28]:
d

array([{'a': 1}, <module 'sys' (built-in)>], dtype=object)

In [29]:
d.dtype

dtype('O')